---
- name: Stop execution of ansible and show how to proceed
  fail:
    msg: >
      Current zendguard integration does not support custom php versions.
      Please disable support of zendguard (php.zendguard.install: false) or
      disable custom php version (remove php.version entry).
  when: php.version

- stat: "path=/usr/lib/php/20131226/zend-loader-php{{ php.version }}-linux-x86_64.tar.gz"
  register: zendGuardArchive

- name: Download the ZendGuard shared object files
  become: yes
  get_url: url="{{ php.zendguard.pkg_url }}" dest="/usr/lib/php/20131226/"
  when: zendGuardArchive.stat.exists == False

- unarchive: "src=/usr/lib/php/20131226/zend-loader-php{{ php.version }}-linux-x86_64.tar.gz dest=/usr/lib/php/20131226/ copy=no"
  become: yes

- copy: "src=/usr/lib/php/20131226/zend-loader-php{{ php.version }}-linux-x86_64/ZendGuardLoader.so dest=/usr/lib/php/20131226/ZendGuardLoader.so remote_src=true"
  become: yes

- copy: "src=/usr/lib/php/20131226/zend-loader-php{{ php.version }}-linux-x86_64/opcache.so dest=/usr/lib/php/20131226/zend_opcache.so remote_src=true"
  become: yes

- name: Place ZendGuard configuration
  become: yes
  template: "src=zend.ini dest=/etc/php/{{ php.version }}/mods-available/zend.ini"

- name: Disable standard PHP opcache
  become: yes
  command: phpdismod opcache
  notify: restart apache

- name: Enable ZendGuard opcache
  become: yes
  command: phpenmod zend
  notify: restart apache
